name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hey, thanks for giving your time to contribute to the project! Try to write an issue as clear as possible.'
        pr-message: 'Hey, thanks for giving your valuable time to modifying the code to make our code better! People like you are the best, and motivate us!'
